var actorsData = [ 
  // Format:
  // ["vo_name", "vo_id", "gender", "accent", "country", "style1", "style2", "style3", "style4"]
	
  
  ["Aakash K.", "aakash_k", "male", "english", "hindu", "narration", "", "", ""],
  ["Aaron G", "aaron_g", "male", "english", "australia", "narration", "", "", ""],
  ["Abbi D", "abbi_d", "female", "english", "united states - texas", "narration", "conversational", "", ""],
  ["Alan T", "alan_t", "male", "english", "england", "narration", "", "", ""],
  ["Alana B", "alana_b", "female", "english", "united states", "narration", "conversational", "", ""],
  ["Ali P", "ali_p", "female", "english", "australia", "narration", "", "", ""],
  ["Anthony A", "anthony_a", "male", "english", "united states", "narration", "conversational", "promo", ""],
  ["Ava M", "ava_m", "female", "english", "united states", "narration", "conversational", "promo", ""],
  ["Bella B", "bella_b", "female", "english", "united states", "narration", "conversational", "promo", ""],
  ["Ben D", "ben_d", "male", "english", "south africa", "narration", "", "", ""],
  ["Benedict M.", "benedict_m", "male", "english", "united kingdom", "narration", "", "", ""],
  ["Cameron S", "cameron_s", "female", "english", "united states", "narration", "", "", ""],
  ["Charlie Z", "charlie_z", "female", "english", "canada", "narration", "", "promo", ""],
  ["Chase J", "chase_j", "male", "english", "united states", "narration", "", "", ""],
  ["Damian P", "damian_p", "male", "english", "canada", "narration", "", "promo", ""],
  ["Diarmid C", "diarmid_c", "male", "english", "scotland", "narration", "conversational", "promo", ""],
  ["Donna W", "donna_w", "female", "english", "united states - appalachia", "narration", "conversational", "", ""],
  ["Eric S", "eric_s", "male", "english", "scotland", "narration", "", "promo", ""],
  ["Fiona H", "fiona_h", "female", "english", "england", "narration", "conversational", "promo", ""],
  ["Frankie P.", "frankie_p", "female", "english", "united kingdom", "narration", "", "", ""],
  ["Garry J", "garry_j", "male", "english", "canada", "", "", "", "character"],
  ["Genevieve M", "genevieve_m", "female", "english", "united states", "narration", "conversational", "promo", ""],
  ["Gia V", "gia_v", "female", "english", "united states", "narration", "conversational", "promo", ""],
  ["Greg G", "greg_g", "male", "english", "australia", "narration", "conversational", "promo", ""],
  ["Hannah A", "hannah_a", "female", "english", "mexico", "narration", "conversational", "", ""],
  ["Isabel V", "isabel_v", "female", "english", "united states", "narration", "", "", ""],
  ["Issa B", "issa_b", "female", "english", "south africa", "narration", "conversational", "", ""],
  ["Jack C", "jack_c", "male", "english", "united states", "narration", "conversational", "", ""],
  ["James B", "james_b", "male", "english", "england", "narration", "conversational", "", ""],
  ["Jarvis H", "jarvis_h", "male", "english", "england", "narration", "conversational", "promo", ""],
  ["Jay S", "jay_s", "male", "english", "united states", "narration", "conversational", "promo", ""],
  ["Jennie V.", "jennie_v", "female", "english", "united states", "narration", "", "", ""],
  ["Jensen X", "jensen_x", "male", "english", "united states", "narration", "", "", ""],
  ["Jeremy G", "jeremy_g", "male", "english", "united states", "narration", "conversational", "", ""],
  ["Jimmy J", "jimmy_j", "male", "english", "united states - southeast", "narration", "conversational", "", ""],
  ["Jodi P", "jodi_p", "female", "english", "united states", "narration", "conversational", "promo", ""],
  ["Joe F", "joe_f", "male", "english", "england", "narration", "conversational", "promo", ""],
  ["Jordan T", "jordan_t", "female", "english", "united states", "narration", "conversational", "promo", ""],
  ["Jude D", "jude_d", "male", "english", "south africa", "narration", "conversational", "", ""],
  ["Kai M", "kai_m", "male", "english", "united states", "narration", "conversational", "", ""],
  ["Kari N", "kari_n", "female", "english", "england", "narration", "", "", "character"],
  ["Lara G.", "lara_g", "female", "english", "australia", "narration", "", "", ""],
  ["Lee M", "lee_m", "male", "english", "united states", "", "conversational", "promo", ""],
  ["Lorenzo D", "lorenzo_d", "male", "english", "mexico", "narration", "conversational", "", ""],
  ["Lulu G", "lulu_g", "male", "english", "united states", "narration", "conversational", "", ""],
  ["Lyric K", "lyric_k", "female", "english", "united states", "narration", "", "", ""],
  ["Marcus G", "marcus_g", "male", "english", "united states", "narration", "conversational", "promo", ""],
  ["Melissa V.", "melissa_v", "female", "english", "united kingdom", "narration", "", "", ""],
  ["Michael V", "michael_v", "male", "english", "united states - mountain west", "narration", "", "", ""],
  ["Nicole L", "nicole_l", "female", "english", "united states", "narration", "conversational", "promo", ""],
  ["Oliver S", "oliver_s", "male", "english", "england", "narration", "conversational", "", ""],
  ["Owen C", "owen_c", "male", "english", "united states - midwest", "narration", "conversational", "promo", ""],
  ["Paige L", "paige_l", "female", "english", "united states", "narration", "conversational", "", ""],
  ["Patrick K.", "patrick_k", "male", "english", "united states", "narration", "conversational", "", ""],
  ["Paul B", "paul_b", "male", "english", "united states", "", "", "promo", ""],
  ["Paula R", "paula_r", "female", "english", "mexico", "narration", "", "promo", ""],
  ["Philip J", "philip_j", "male", "english", "united states", "narration", "conversational", "promo", ""],
  ["Rachin K.", "rachin_k", "male", "english", "hindu", "", "conversational", "", ""],
  ["Raine B", "raine_b", "male", "english", "united states", "narration", "", "", ""],
  ["Ramona J", "ramona_j", "female", "english", "united states", "narration", "conversational", "promo", ""],
  ["Rayna C.", "rayna_c", "female", "english", "united states", "narration", "", "", ""],
  ["Rohini B.", "rohini_b", "female", "english", "hindu", "narration", "", "", ""],
  ["Selene R", "selene_r", "female", "english", "united states", "narration", "", "promo", ""],
  ["Se'von M", "sevon_m", "male", "english", "united states", "narration", "", "", ""],
  ["Shelby D", "shelby_d", "female", "english", "united states", "narration", "conversational", "promo", ""],
  ["Sofia H", "sofia_h", "female", "english", "united states", "narration", "conversational", "promo", ""],
  ["Sonny G.", "sonny_g", "male", "english", "australia", "narration", "", "", ""],
  ["Spiti V.", "spiti_v", "female", "english", "hindu", "narration", "", "", ""],
  ["Steve B", "steve_b", "male", "english", "united states", "", "", "promo", ""],
  ["Terra G", "terra_g", "female", "english", "united states", "narration", "conversational", "promo", ""],
  ["Theo K", "theo_k", "male", "english", "australia", "narration", "", "", ""],
  ["Tilda C", "tilda_c", "female", "english", "united states", "narration", "conversational", "promo", ""],
  ["Tobin A", "tobin_a", "male", "english", "united states", "narration", "", "promo", ""],
  ["Tosh M.", "tosh_m", "male", "english", "united states", "", "conversational", "", ""],
  ["Tristan F", "tristan_f", "male", "english", "united states", "narration", "", "", ""],
  ["Vanessa N", "vanessa_n", "female", "english", "united states", "narration", "conversational", "promo", ""],
  ["Veer S", "veer_s", "male", "english", "hindu", "", "", "promo", ""],
  ["Wade C", "wade_c", "male", "english", "united states", "narration", "conversational", "promo", ""],
  ["Zach E", "zach_e", "male", "english", "united states", "narration", "", "promo", ""],
  ["Zoey O", "zoey_o", "female", "english", "australia", "narration", "", "", ""]


];


actorsData;
